# Main

title: SygWave
description: The homepage of SygWave
author: SygWave

# Nav

navbar-links:
  About: "about"
  Contact: "contact"

# Logo

#avatar: "/assets/images/logo-square.png"
round-avatar: false
title-img: /assets/images/logo-round.png

# Footer

social-network-links:
  #email: ""
  github: sygwave
  rss: false

# Options

share-links-active:
  github: true

url-pretty: "sygwave.github.io"
link-tags: true
excerpt_length: 50

# Background

navbar-col: "#121212"
navbar-text-col: "#000000"
navbar-border-col: "#000000"
page-col: "#C278C2"
link-col: "#1BE9D2"
hover-col: "#05F9AC"
footer-col: "#121212"
footer-text-col: "#000000"
footer-link-col: "#1BE9D2"

#navbar-img: "/assets/images/..."
#footer-img: "/assets/images/..."
#page-img: "/assets/images/..."

# Web

#gtag: ""
#google_analytics: ""
#gtm: ""

# Miscellaneous

title-separator: "-"
date_format: "%B %-d, %Y"

# Output
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
kramdown:
  input: GFM

# YAML
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      social-share: true
      readtime: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      show-avatar: true

exclude:
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap